#%RAML 0.8
title: Authorization service - manages groups of client/user specific claims
version: 1
/clients:
  get:
    description: Retrieves a list of registered clients
  post:
    description: Adds a client to the user store
    body:
      application/json:       
        example: |      
          {
            "id": "clientid",
            "name": "clientname",
            "enabled": true,
            "claimsUri": "http://<host>/claims"
          }    
/clients/{clientId}:
  get:
    description: Gets the specified client
    responses:
      200:
        body:
          application/json:
            example: |
              {
                "id": "clientid",
                "name: "clientname",
                "enabled": true,
                "claimsUri": "http://<host>/claims"
              }
  put:
    description: Updates the specified client 
    body:
      application/json:
        example: |
          {
            "id": "clientid",
            "name": "clientname",
            "enabled": true,
            "claimsUri": "http://<host>/claims"                    
          }
  delete:
    description: Deletes the specified client
/clients/{clientId}/groups:
  get:
    description: Gets the collection of groups
    body:
      application/json:
        example: |
          "id": "...",
          "name": "..."
  post:
    description: Adds a group to the client
/clients/{clientId}/groups/{groupId}:
  get:
    description: Gets the specified group for the specified client
  put:
  delete:
/clients/{clientId}/groups/{groupId}/claims:
  get:
    description: Gets the claims for the specified group
  post:
/clients/{clientId}/groups/{groupId}/claims/{claimId}:
  get:
    description: Gets the specified claim within the specified group
    responses:
      200:
        body:
          application/json:
            example: |
              {
                "id": "...",
                "type": "...",
                "value": "..."
              }
  put:
    description: Updates the specified claim within the specified group
    body:
      application/json:
        example: |
          {
            "type": "...",
            "value": "..."
          }
  delete:
    description: Deletes the specified claim within the specified group
/clients/{clientId}/groups/{groupId}/users:
  get:
    description: Gets the users belonging to the specified group
    responses:
      200:
        body:
          application/json:
            example: |
              [
               {
                "id": "...",
                "username": ..."            
               } 
              ]
  post:
    description: Adds a user to the specified group
    body:
      application/json:
        example: |
          {
            "id": "..."
          }
/clients/{clientId}/groups/{groupId}/users/{userId}:
  get:
    description: Gets the user belonging to the specified group
    responses:
      200:
        body:
          application/json:
            example: |
              {
                "id": "...",
                "username": "..."                
              }
  delete:
    description: Deletes the user from the specified group    
/users:
  get:
    description: Gets the users
/users/{userId}/groups:
  get:
    description: Gets the collection of groups that the specified user belongs to
    queryParameters:
      clientId:
        description: Filters groups by the specified client id
        required: false      
    body:
      application/json:
        example: |
          [
            {
              "clientId": "..."
              "id": "...",
              "name": "..."
            },
            {
              "clientId": "..."
              "id": "...",
              "name": "..."
            }
          ]
/users/{userId}/claims:
  get:
    description: Gets the collection of claims that the user has
    queryParameters:
      clientId:
        description: Filters claims by the specified client id
        required: false
    body:
      application/json:
        example: |
          [
            {
              "clientId": "...",
              "id": "...",
              "type": "...",
              "value": "..."
            }
          ]