#%RAML 0.8
title: User service - manages users and user claims
version: 1
/users:
  get:
    description: Retrieves the list of users from the user store
  post:
    description: Adds a user to the user store
    body:
      application/json:       
        example: |      
          {
            "id": "user",
            "password": "..."            
          }
    responses:
      201:
        body:
          application/json:
            example: |
              {
                "id": "user"
              }
/users/{userId}:
  get:
    description: Gets the specified user from the user store
    responses:
      200:
        body:
          application/json:
            example: |
              {
                "id": "user"
              }
  put:
    description: Updates the specified user in the user store
    body:
      application/json:
        example: |
          {
            "password": "..."
          }
    responses:
      204:
  delete:
    description: Deletes the specified user from the user store
    responses:
      204:
/users/{userId}/claims:
  get:
  post:
    description: Adds a claim to the specified user
    body:
    responses:
      204:
/users/{userId}/claims/{claimId}:
  get:
  put:
  delete:
/users/{userId}/authentiate:
  post:
    description: Authenticates the user
	body:
	  application/json:
	    example: |
		  {
		    "password": "..."
		  }
	responses:
	  200:
	  400: